In [24]:
import pandas as aju
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits,load_iris
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold,cross_val_score,StratifiedKFold
import numpy as np

In [2]:
digit = load_digits()

In [3]:
x_train,x_test,y_train,y_test = train_test_split(digit.data,digit.target,test_size = 0.2,random_state = 99)

In [4]:
model = LogisticRegression(C=100)
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9805555555555555

In [5]:
rfc = RandomForestClassifier()
rfc.fit(x_train,y_train)
rfc.score(x_test,y_test)

0.9833333333333333

In [6]:
svc = SVC()
svc.fit(x_train,y_train)
svc.score(x_test,y_test)

0.9888888888888889

In [7]:
kf = KFold(n_splits =3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)
# since the n_splits = 3; 1 to 9 was divided into 3 splits like 0 1 2 | 3 4 5| 6 7 8 
# 2 folds for training and 1 for testing

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [9]:
def model_score(mod,x_train,x_test,y_train,y_test):
    mod.fit(x_train,y_train)
    return mod.score(x_test,y_test)

In [10]:
model_score(model,x_train,x_test,y_train,y_test)

0.9805555555555555

In [11]:
model_score(rfc,x_train,x_test,y_train,y_test)

0.9777777777777777

In [12]:
model_score(svc,x_train,x_test,y_train,y_test)

0.9888888888888889

In [13]:
score_lr = []
score_rfc = []
score_svc = []
for train_index,test_index in kf.split(digit.data):
    x_train,x_test,y_train,y_test = digit.data[train_index],digit.data[test_index],digit.target[train_index],digit.target[test_index]
    score_lr.append(model_score(model,x_train,x_test,y_train,y_test))
    score_rfc.append(model_score(rfc,x_train,x_test,y_train,y_test))
    score_svc.append(model_score(svc,x_train,x_test,y_train,y_test))
    

In [14]:
score_lr

[0.9081803005008348, 0.9382303839732888, 0.8998330550918197]

In [15]:
score_rfc

[0.9348914858096828, 0.9532554257095158, 0.9215358931552587]

In [16]:
score_svc

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [17]:
cross_val_score(LogisticRegression(),digit.data,digit.target)

E:\Program_files_x64\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
E:\Program_files_x64\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [18]:
iris = load_iris()

In [19]:
v = cross_val_score(LogisticRegression(),iris.data,iris.target)
print(v,np.average(v))

[0.96666667 1.         0.93333333 0.96666667 1.        ] 0.9733333333333334


E:\Program_files_x64\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [20]:
s = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
np.average(s)

0.9600000000000002

In [21]:
c = cross_val_score(RandomForestClassifier(),iris.data,iris.target)
np.average(c)

0.9666666666666668

In [22]:
y = cross_val_score(SVC(),iris.data,iris.target)
np.average(y)

0.9666666666666666

In [ ]:
skf = StratifiedKFold(n_splits = 3,shuffle = True)
skf

In [ ]:
x = [12,23,12,22,11,44,55,2,11,33,20,77]
y = [0,1,0,1,0,1,0,1,1,0,1,0]
for i,j in skf.split(x,y):
    print(i,j)